import pygame, sys
from pygame.locals import QUIT
import turtle
pygame.init()
screen = pygame.display.set_mode()
t = turtle.Turtle()
window = turtle.Screen()
window.screensize(canvwidth=400, canvheight=400, bg="light blue")
t.speed(100)
t.shape('arrow')
t.penup()
t.goto(-350,-75)
t.pendown()
t.color('black', 'green')
t.begin_fill()
t.fd(700)
t.right(90)
t.fd(250)
t.rt(90)
t.fd(700)
t.rt(90)
t.fd(250)
t.end_fill()
t.color('yellow')
t.penup()
t.goto(-200, 150)
t.pendown()
t.begin_fill()
t.circle(50)
t.end_fill()
t.penup()
t.lt(90)
t.fd(30)

def main():
  person('purple',15,250)
  person('blue', 10, 150)
  person('green', 8, 50)
  person('yellow', 17, -50)
  person('orange', 15, -150)
  person('red', 10, -250)

  
def person(color, line_width, xpos):
  p = turtle.Turtle()
  p.color(color)
  p.width(line_width)
  p.penup()
  p.goto(xpos, -75)
  p.pendown()
  p.lt(120)
  p.fd(35)
  p.lt(120)
  p.fd(35)
  p.left(180)
  p.fd(35)
  p.lt(30)
  p.fd(20)
  p.rt(105)
  p.fd(20)
  p.bk(40)
  p.fd(20)
  p.lt(105)
  p.fd(15)
  p.right(90)
  p.begin_fill()
  p.circle(15)
  p.end_fill()
  p.penup()
  p.lt(90)
  p.fd(25)
  p.left(90)
  p.fd(7)
  p.pendown()
  if color == "black":
    p.width(2)
    p.color("white")
    p.begin_fill()
    p.circle(4)
    p.end_fill()
    p.penup()
    p.bk(14)
    p.pendown()
    p.begin_fill()
    p.circle(4)
    p.end_fill()
    p.penup()
    p.fd(7)
    p.lt(90)
    p.fd(15)
    p.lt(90)
    p.pendown()
    p.fd(5)
    p.bk(10)
  else:
    p.width(2)
    p.color("black")
    p.begin_fill()
    p.circle(4)
    p.end_fill()
    p.penup()
    p.bk(14)
    p.pendown()
    p.begin_fill()
    p.circle(4)
    p.end_fill()
    p.penup()
    p.fd(7)
    p.lt(90)
    p.fd(15)
    p.lt(90)
    p.pendown()
    p.fd(5)
    p.bk(10)
  p.color(color)
  p.penup()
  p.goto(xpos, -75)
  p.fd(20)
  p.width(30)
  p.color("saddlebrown")
  p.pendown()
  p.fd(20)
  p.width(5)
  p.rt(90)
  p.color('black', 'saddlebrown')
  p.begin_fill()
  p.circle(16)
  p.end_fill()
  p.lt(90)
  p.width(2)
  p.penup()
  p.fd(12)
  p.pendown()
  p.circle(2)
  p.penup()
  p.fd(8)
  p.pendown()
  p.circle(2)
  p.right(90)
  p.penup()
  p.fd(8)
  p.pendown()
  p.right(90)
  p.fd(8)
  p.penup()
  p.fd(20)
  p.lt(90)
  p.pendown()
  p.width(5)
  p.color('black')
  p.fd(15)
  p.bk(15)
  p.rt(90)
  p.penup()
  p.fd(12)
  p.lt(90)
  p.pendown()
  p.fd(15)
  


main()
while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
    pygame.display.update()